"""统一业务错误码（与 docs/api.md §0.1 一致）。"""

from enum import StrEnum


class ErrorCode(StrEnum):
    """业务错误码，随 4xx/5xx 响应体返回。"""

    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    FORBIDDEN_SCOPE = "FORBIDDEN_SCOPE"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INVALID_STATE = "INVALID_STATE"
    DUPLICATE_SUBMIT = "DUPLICATE_SUBMIT"
    DUPLICATE_INVOICE = "DUPLICATE_INVOICE"
    RESOURCE_CONFLICT = "RESOURCE_CONFLICT"
    REPORT_NOT_READY = "REPORT_NOT_READY"
    INTERNAL_ERROR = "INTERNAL_ERROR"
